Backbase/variants

- .github/workflows/branch.yml
- .github/workflows/danger-swift.yml
- Dangerfile.swift
- Package.swift
- Sources/VariantsCore/Helpers/Bash.swift
- Tests/LinuxMain.swift
- Tests/VariantsTests/VariantsTests.swift
- Tests/VariantsTests/XCTestManifests.swift
- Adds [Danger](https://danger.systems/swift/) to automate common code review chores.
- Run locally, `swift run danger-swift local`.
> Add Danger to automate code review chores

- .github/workflows/danger-swift.yml
- .github/workflows/swiftlint.yml
- Add `DANGER_GITHUB_API_TOKEN` as environment variable to Danger, so that @backbaseoss can post comments on Danger's behalf.
> Attempt to integrate Danger comments directly in PRs

- Sources/VariantsCore/Custom Types/Project/AndroidProject.swift
- Tests/VariantsCoreTests/AndroidProjectTests.swift
- Creates gradle script even when `skipFastlane` is set to true
Running `make validation` and `swift run danger-swift local` should not return any error
resolves #93
> Create gradle script even when skipFastlane is set to true

- Sources/VariantsCore/Custom Types/Project/AndroidProject.swift
- Sources/VariantsCore/Helpers/Constants.swift
- Tests/VariantsCoreTests/AndroidProjectTests.swift
- Directly populate `fastlane/parameters/variants_params.rb` with `"PACKAGE_NAME"` so that Fastlane can use when deploying to PlayStore.
- Running `variants setup` or `variants switch` for an Android project should result in `variants_params.rb` containing the property `"PACKAGE_NAME"`.
resolves #80
> Populate package name in 'variants_params.rb'

- Sources/VariantsCore/Schemas/Android/AndroidConfiguration.swift
- Sources/VariantsCore/Schemas/Android/AndroidVariant.swift
- Sources/VariantsCore/Schemas/iOS/iOSConfiguration.swift
- Sources/VariantsCore/Schemas/iOS/iOSVariant.swift
- Templates/android/variants-template.yml
- Templates/ios/variants-template.yml
- Tests/VariantsCoreTests/GradleScriptFactoryTests.swift
- Tests/VariantsCoreTests/Resources/invalid_variants.yml
- Tests/VariantsCoreTests/Resources/ios/invalid_missing_export_method.yml
- Tests/VariantsCoreTests/Resources/ios/invalid_missing_signing_configuration.yml
- Tests/VariantsCoreTests/Resources/valid_variants.yml
- Tests/VariantsCoreTests/Resources/variants-template.yml
- Tests/VariantsCoreTests/YamlParserTests.swift
- docs/CUSTOM_PROPERTY.md
- docs/STORE_DESTINATION.md
- docs/USAGE.md
- docs/ios/WORKING_WITH_FASTLANE_MATCH.md
- Changes list of variants in `variants.yml` from array to dictionary
- Updates docs and resources accordingly
resolves #114
> Changes list of variants in `variants.yml` from array to dictionary

- Sources/VariantsCore/Factory/iOS/XCConfigFactory.swift
- Sources/VariantsCore/Schemas/iOS/iOSSigning.swift
- Sources/VariantsCore/Schemas/iOS/iOSVariant.swift
- Automatically populate 'PROVISIONING_PROFILE_SPECIFIER' if using match in signing configuration
resolves #117
> feat: automatically populate 'PROVISIONING_PROFILE_SPECIFIER' if using match in signing configuration

- Gemfile
- Gemfile.lock
- Templates/ios/_fastlane/Gemfile
- Templates/ios/_fastlane/Gemfile.lock
- Update `nokogiri` to version 1.11.0 due to [this low severity vulnerability](https://github.com/advisories/GHSA-vr8q-g5c7-m54m)
> Update nokogiri to 1.11.0 due to vulnerability

- Sources/VariantsCore/Helpers/SpecHelper.swift
- Improve warnings during execution of `variants init`
- Specify which fields in `variants.yml` couldn't be populated automatically for iOS
- Adhere to the [latest changes](https://github.com/Backbase/variants/commit/2bad20dc1ab9ac6275daf6db6e1ba475931063bb#diff-88e254e2c28df11e815768543a21790e7d60b64b331abcf1d324ef6f768e4043) in variants.yml
- Run `variants init` on the base folder of an iOS project that doesn't contain `variants.yml`
resolves #115
> Improve warnings during `variants init`

- Makefile
- Sources/VariantsCore/Commands/Initializer.swift
- Sources/VariantsCore/Commands/Setup.swift
- Sources/VariantsCore/Commands/Switch.swift
- Sources/VariantsCore/Factory/ProjectFactory.swift
- Sources/VariantsCore/Helpers/SpecHelper.swift
- Sources/VariantsCore/Loggers/Logger.swift
- Sources/VariantsCore/Loggers/VerboseLogger.swift
- Tests/VariantsCoreTests/AndroidProjectTests.swift
- Tests/VariantsCoreTests/ProjectFactoryTests.swift
- Tests/VariantsCoreTests/SpecHelperTests.swift
- Tests/VariantsCoreTests/iOSProjectTests.swift
- Tests/VariantsTests/InitCommandTests.swift
- Tests/VariantsTests/VariantsTests.swift
- Variants.xcodeproj/project.pbxproj
- docs/USAGE.md
- Introduce argument `-t | --timestamps` and only show timestamps on console logs when it's present
- Run `variants init`
- Run `variants init --timestamps`
resolves #130
> Improve timestamps

- Sources/VariantsCore/Custom Types/Project/AndroidProject.swift
- Sources/VariantsCore/Custom Types/TemplateDirectory.swift
- Sources/VariantsCore/Custom Types/UtilsDirectory.swift
- Sources/VariantsCore/Factory/FastlaneParametersFactory.swift
- Sources/VariantsCore/Loggers/Logger.swift
- Sources/VariantsCore/Schemas/Android/AndroidConfiguration.swift
- codecov.yml
- Decodes `android.signing` as optional
- Writes `fastlane/` in the base folder regardless of the path in `android.path`
- Throws `RuntimeError` with more descriptive error message when writing to fastlane parameter files
- Removes redundant ❌ when instantiating RuntimeError
- Generate new spec with `variants init`
- Replace the following placeholders with correct value:
- `android.path`
- `android.app_name`
- `android.app_identifier`
- Run `variants setup`
> Fix `variants setup` for Android

- .github/workflows/ci.yml
- Tests/VariantsCoreTests/AndroidProjectTests.swift
- Tests/VariantsCoreTests/FastlaneParametersFactoryTests.swift
- Tests/VariantsCoreTests/iOSProjectTests.swift
Update Github's CI workflow configuration file to use latest Xcode app.
Sidenote:
1. The UnitTests were failing due to `mkpath()` in the test `testFileWrite_correctOutput` from `FastlaneParametersFactoryTests`. This was happening due to the method creating the complete path as a directory, resulting in the file being created as a directory.
2. Small refactor in the `AndroidProjectTests` and `iOSProjectTests` classes to improve readability.
This updates the CI config so no test is required as long as the CI is working.
Fixes #160
> Update GitHub workflow config yml

- Sources/VariantsCore/Custom Types/TemplateDirectory.swift
- Sources/VariantsCore/Custom Types/UtilsDirectory.swift
- Dynamically finds the tools' installation path, therefore able to infer the root path of `lib/variants/templates`.
- [Install Variants via homebrew on Apple Silicon](https://github.com/Backbase/variants#homebrew-recommended).
- Run `variants init` on a new project.
- It should no longer fail as reported in issue #177
resolves #177
> fix: inability to find 'Templates' folder when installing Variants with homebrew on Apple Silicon

- .github/workflows/branch.yml
- Makefile
- Builds a fat binary for archs x86-64 and arm64
- Make build should generate a binary that contains both archs. Can be tested with `lipo -info path/to/variants`
> feat: build fat binary for archs arm64 and x86_64

- Sources/VariantsCore/Custom Types/Project/iOSProject.swift
- Sources/VariantsCore/Factory/iOS/XcodeProjFactory.swift
- Sources/VariantsCore/Helpers/SpecHelper.swift
- Sources/VariantsCore/Schemas/iOS/iOSConfiguration.swift
- Sources/VariantsCore/Schemas/iOS/iOSSigning.swift
- Sources/VariantsCore/Schemas/iOS/iOSTarget.swift
- Sources/VariantsCore/Schemas/iOS/iOSVariant.swift
- Tests/VariantsCoreTests/FastlaneParametersFactoryTests.swift
- Tests/VariantsCoreTests/Mocks/MockXCcodeConfigFactory.swift
- Tests/VariantsCoreTests/YamlParserTests.swift
- Tests/VariantsCoreTests/iOSProjectTests.swift
- Tests/VariantsCoreTests/iOSSigningTests.swift
- Tests/VariantsCoreTests/iOSVariantTests.swift
- Tests/VariantsTests/InitCommandTests.swift
- samples/ios/VariantsTestApp/VariantsTestApp/AppDelegate.swift
- samples/ios/VariantsTestApp/VariantsTestApp/SceneDelegate.swift
- samples/ios/VariantsTestApp/VariantsTestApp/Variants/Variants.swift
- samples/ios/VariantsTestApp/VariantsTestApp/ViewController.swift
- This PR sorts the generated xcconfig file, to make sure that it's not random every time we generate a new one, this will make things easier to see what exactly changed in the xcconfig file between variants.
To test this PR, you can switch the variant, and see if the xcconfig file is sorted alphabetically.
resolves #219
> Fix xcconfig randomly sorted generation

- Sources/VariantsCore/Factory/iOS/XCConfigFactory.swift
- Sources/VariantsCore/Helpers/Constants.swift
- This PR is to add the feature where configs of Cocoa Pods are imported in variants.xcconfig only if Pods file is present, and if the config in Target Support Files is also present.
We can run variants switch on a project with a Podfile and the config in `./Pods/Target Support Files/...` is present and check if the `#include ...` is added at the top of the variants.xcconfig file,
and then run variants switch on a project without a Podfile ( `#include ...` shouldn't be there )
and then run variants switch on a project with a Podfile but without the config in `./Pods/Target Support Files/...`, you should receive an error in the terminal
No task for this one
> Supporting variants and pods configs simultaneously

- Package.swift
- Sources/VariantsCore/Schemas/iOS/iOSVariant.swift
- Tests/VariantsCoreTests/FastlaneParametersFactoryTests.swift
- Tests/VariantsCoreTests/VariantsFileFactoryTests.swift
- Tests/VariantsCoreTests/XcodeProjFactoryTests.swift
- Tests/VariantsCoreTests/iOSVariantTests.swift
- docs/USAGE.md
- Enable the ability to override the default name for each variant
1 . Add the `app_name` field  to `samples/ios/VariantsTestApp/variants.yml` to either the `default` or `beta` variant
2. cd `samples/ios/VariantsTestApp/` 
3. switch to this variant: `swift run variants switch --variant <variant>`
4. you should notice in `samples/ios/VariantsTestApp/VariantsTestApp/Variants/variants.xcconfig` that the `V_APP_NAME` is equal to the value that you had previously set for `app_name`
resolved https://github.com/Backbase/variants/issues/216
> [216] Add ability to override app name per variant

- Sources/VariantsCore/Custom Types/Project/iOSProject.swift
- Sources/VariantsCore/Schemas/iOS/iOSConfiguration.swift
- Sources/VariantsCore/Schemas/iOS/iOSVariant.swift
- Tests/VariantsCoreTests/FastlaneParametersFactoryTests.swift
- Tests/VariantsCoreTests/VariantsFileFactoryTests.swift
- Tests/VariantsCoreTests/XcodeProjFactoryTests.swift
- Tests/VariantsCoreTests/iOSVariantTests.swift
- docs/USAGE.md
- docs/ios/POST_SWITCH_SCRIPT.md
- in this PR, post switch script is added, so whenever a user wants to run a specific script after switching variants, they can either do that for a specific variant, or for global switching, or for both
- if the user specifies both variant specific and global postSwitchScript, we will run the variants specific one first and then the global one
add a postSwitchScript to your variants.yml and it will be executed
- Add one postSwitchScript in a variant
- Add another one on the global layer of the yaml file
- Remove both to make sure that it's optional
resolves #X (where `#X` is the number of an issue)
> Add PostSwitchScript to iOSConfiguration and to iOSVariant

- Sources/VariantsCore/Factory/iOS/XCConfigFactory.swift
- Sources/VariantsCore/Helpers/Constants.swift
reverted changes to fix bug which caused the UITests project to import an unneeded pod used by the app project, since the xcconfig is shared between the app and the tests projects
-
Tell us how to test these changes
resolves #X (where `#X` is the number of an issue)
> Reverting supporting-variants-and-pods-configs-simultaneously

- Sources/Variants/main.swift
- docs/GITHUB_ACTION.md
> chore: version bump to 1.2.1

- .github/workflows/danger-swift.yml
- .github/workflows/swiftlint.yml
- Package.swift
- README.md
- Sources/VariantsCore/Custom Types/Project/AndroidProject.swift
- Sources/VariantsCore/Custom Types/Project/iOSProject.swift
- Sources/VariantsCore/Factory/iOS/VariantsFileFactory.swift
- Sources/VariantsCore/Helpers/Bash.swift
- Sources/VariantsCore/Helpers/SpecHelper.swift
- Sources/VariantsCore/Schemas/iOS/iOSConfiguration.swift
- Sources/VariantsCore/Schemas/iOS/iOSSigning.swift
- Sources/VariantsCore/Schemas/iOS/iOSTarget.swift
- Sources/VariantsCore/Schemas/iOS/iOSVariant.swift
- Templates/ios/Variants.swift.template.gyb
- Tests/VariantsCoreTests/Mocks/MockXCcodeConfigFactory.swift
- Tests/VariantsCoreTests/VariantsFileFactoryTests.swift
- Tests/VariantsCoreTests/YamlParserTests.swift
- Tests/VariantsCoreTests/iOSProjectTests.swift
- Tests/VariantsCoreTests/iOSSigningTests.swift
- Tests/VariantsTests/InitCommandTests.swift
- Variants.xcodeproj/project.pbxproj
- samples/ios/VariantsTestApp/VariantsTestApp/ViewController.swift
- utils/gyb
- When capturing the output of a Bash command, select either `stdout` or `stderr` to be captured.
- Require `python2.7` to run `gyb` and default to a `fatalError` if not available. This prints an appropriate message to the user.
- It defaults to a `fatalError` when generating `Variants.Secrets` if environment variable used by a custom config doesn't exist.
- Run `variants switch` or `variants setup` without `python2.7` installed or in your executables path.
- Run `variants switch` or `variants setup` with at least one custom config whose `env: true` but `value` points to a non-existing environment variable.
Resolves #204 
Resolves #240
> Fix Code Generation with GYB
